have_fun: true
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: 20
  pull_request_opened:
    help: false
    summary: true
    code_review: true
  language: "ja"  # レビューコメントを日本語で出力
  comment_style:
    format: "日本語"
    tone: "professional"
    include_emojis: false 